### ISSUE TITLE
Compiler Error CS0121 - MilvusClient is ambiguous

### ISSUE THREAD

**Issue by Kaotic3** [milvus-io/milvus-sdk-csharp#26]
**Describe the bug**

When following along with the Quick Start using 2.2.2-preview.1, it appears that MilvusClient cannot determine which MilvusClient to use.

"CS0121: The call is ambiguous between the following methods or properties: "MilvusClient.MilvusClient(string, int, string?, string?, CallOptions, ILoggerFactory?) and MilvusClient.MilvusClient(string, int, string?, string?, CallOptions, ILoggerFactory?)

**Potential problem:**

There doesn't appear to be any difference in the code between the gRPC and the Resftul client within the "Quick Start" guide.  It is exactly the same code.  I can't see a way to differentiate, since you do separate these out into different headers - I would have expected a difference?

You also call the client "client" but then refer to it as "milvusClient" - I only mention so that if you look at it and it needs updating you can update that part too.

Please do not think this is a criticism, it is not, I was really happy when I found this repo

I also got it working on the 2.2.1-alpha.7 version, as that is in the notebooks that you provide, so I know that Milvus is up and running and I can do a successful health check.

**To Reproduce**

Copy and paste the Quick Start code into a console application.

**Comment by Kaotic3** [comment]
Ok, so typically - 2 secs after posting this I fixed the issue.

I was using:
new MilvusClient("endPoint", "port", null, null)

I thought I would try to get to the CallOptions, to see if I could set them to fit my needs, so I put in:

new MilvusClient("endPoint", "port", null, null, null)

And it works, no more compiler error and my HealthAsync call is successful.

**Comment by weianweigan** [comment]
Sorry for the inconvenience caused. We have used a new API in version 2.2.2, but the documentation is still for version 2.2.1.
Version 2.2.2 has updated a lot of content, including the removal of support for Restful APIs. We will update the documentation and NuGet packages in the next few days.
It is recommended that you use the latest 2.2.2 version because it has passed more tests and better api, but existing notebooks may not be useful as a reference anymore.

**Comment by Kaotic3** [comment]
Thanks for the response, appreciate it.

Been looking at your tests as a sort of guide - and I have it connecting and returning data...but I am having a problem getting to the final step.

I can see, through brute force, that Data as a List exists as a property of the DataTypes.

So:

`foreach (var hit in results.FieldsData)
{
    foreach (var prop in hit.GetType().GetProperties())
    {
        Console.Wireline($"{prop.Name}: {prop.GetValue(hit)}
    }
}`

Provides the output:

Data: ["FieldValue1", "FieldValue2", etc...]

But this is the only way I can access it.

I feel that Data should be a property to the FieldData so that you can access it directly via the "hit.Data" - but there is no such property?

**Comment by weianweigan** [comment]
FieldData is a abstract class that stores data for different data type. If you want to access  **Data** property, you need convert it to **FieldData<TData>**.

**Comment by Kaotic3** [comment]
Apologies Weianweigan, I do not follow.

This is my code:

![image](https://github.com/milvus-io/milvus-sdk-csharp/assets/80522225/492afed9-445e-417a-9647-30dd90fbafa6)

Which is a "SearchResults" return.

Within SearchResults you have:

![image](https://github.com/milvus-io/milvus-sdk-csharp/assets/80522225/f17388c6-5cb4-48bf-b468-04910e46d374)

There are a few other properties here - but this is the only relevant one.

Going into the FieldData - you have this:

![image](https://github.com/milvus-io/milvus-sdk-csharp/assets/80522225/71c4e5b5-04de-408c-a4fb-e25b24a722c9)

I don't see Data anywhere as an accessible field.

Which is odd, because when I run the code, I see: 

![image](https://github.com/milvus-io/milvus-sdk-csharp/assets/80522225/5923cc18-8f1d-45ef-a028-c43afc309482)

Which indicates a Data property, but I can't access it.

I apologise if I am missing something.

**Comment by weianweigan** [comment]
When you get hit in for each loop, you need to convert it to your data type. It depends your collection schema. Such as

```
var stringField = hit as FieldData<string>
```
Then you can find data property in  stringField
But it's not a good idea that convert it in a loop. Maybe you need get it from index then convert it based on you collection schema.
