### PR TITLE
Fix build and parallel-execution race on main

### PR DESCRIPTION
**Pull request by N-E-W-T-O-N**
## Problem

`main` is red. Two separate post-merge problems, both fallout from #134 and #136 landing together.

### 1. Build failure — 62 × `xUnit1051` in `Bm25Tests.cs`

```
Bm25Tests.cs(19,15): error xUnit1051: Calls to methods which accept CancellationToken
should use TestContext.Current.CancellationToken ...
```

A semantic merge conflict between two PRs that were each green alone:

- **#134 (BM25)** added `Bm25Tests.cs`, written against xunit v2 — no `TestContext.Current.CancellationToken`.
- **#136 (xunit.v3)** enabled the `xUnit1051` analyzer, which is a **build error** here because `TreatWarningsAsErrors` is on.

`Bm25Tests.cs` did not exist when #136 was written, so its call sites were never migrated. Git merged both cleanly; the rule from #136 then applied to the new file from #134.

This broke **all four** matrix versions — the reported v2.4.23 job merely failed first, and fail-fast cancelled the rest.

### 2. Test failure — `DataTests.FlushAllAsync_and_wait`

```
ErrorCode: 65535 ... failed to call flush all to data coordinator: collection not found
```

`FlushAll` is cluster-wide: it enumerates and flushes every collection in the instance. Every other test class creates and drops collections, so once #136 made the classes run in parallel, this test could see a collection disappear mid-flush.

It is timing-dependent — it failed on v2.5.20 while v2.3.22 and v2.6.4 passed. It surfaced now because this was the first run after #136 in which the build got far enough to execute tests.

## Fix

1. Thread `TestContext.Current.CancellationToken` through all 62 call sites in `Bm25Tests.cs`. Named `cancellationToken:` is used **only** where an intermediate optional parameter is skipped (e.g. `CreateIndexAsync` passing `extraParams:` without `indexName`, `CreateCollectionAsync` skipping `consistencyLevel`/`shardsNum`, `InsertAsync` skipping `partitionName`); positional everywhere else. This item carries no behavioural change.
2. Put `DataTests` in a collection with `DisableParallelization` so the global flush sees a stable set of collections.
3. Drop the now-dangling `[Collection("Milvus")]` from `Bm25Tests` — #136 removed the matching `MilvusTestCollection` definition.

> **Scope note:** items 2 and 3 *are* behavioural changes to the test suite — `DataTests` no longer runs concurrently with the other classes. That is deliberate (the cluster-wide `FlushAll` needs a stable set of collections), but it is a real change in how the suite executes, not a mechanical token edit.

## Verification

- Build: clean, 0 errors / 0 warnings, all TFMs
- `Bm25Tests` against Milvus v2.6.4: **9/9 passing**
- Full suite against v2.6.4, run **twice** to check the race actually holds: **200 passed, 1 skipped, 0 failed** both times (the skip is the pre-existing `Query_with_time_travel`)

### CODE REVIEW

File: Milvus.Client.Tests/Bm25Tests.cs [hunk 1]
```diff
@@ -63,7 +64,8 @@ await collection.WaitForCollectionLoadAsync(
             {
                 ConsistencyLevel = ConsistencyLevel.Strong,
                 OutputFields = { "text" }
-            });
+            },
+            cancellationToken: TestContext.Current.CancellationToken);
```
Comment (yhmo) [inline Milvus.Client.Tests/Bm25Tests.cs]: Milvus.Client.Tests/Bm25Tests.cs line:68
Low ---- Minor style inconsistency with the convention described in the PR description ("named `cancellationToken:` where intermediate optional parameters are skipped, positional otherwise"): identical call shapes in this file mix both styles — named here and at lines ~135/~201/~625, positional at ~322/~402/~482/~552. No optional parameter is skipped in any of these calls, so the positional form would match the stated rule in every case. Not a correctness issue, but unifying the same-shape calls would keep the file internally consistent.

File: Milvus.Client.Tests/DataTests.cs [hunk 2]
```diff
@@ -2,6 +2,14 @@
 
 namespace Milvus.Client.Tests;
 
+// FlushAllAsync_and_wait calls the cluster-wide FlushAll, which enumerates and flushes every
+// collection in the instance. All the other test classes create and drop collections, so if any of
+// them runs concurrently the flush fails with "collection not found". Keep this class out of the
+// parallel pool so the global flush sees a stable set of collections.
+[CollectionDefinition(nameof(DataTests), DisableParallelization = true)]
```
Comment (yhmo) [inline Milvus.Client.Tests/DataTests.cs:9]: Milvus.Client.Tests/DataTests.cs line:9
Low ---- The PR title/description ("Thread cancellation tokens through Bm25Tests", "No behavioural change") does not cover this change. Putting DataTests into a `DisableParallelization` collection is a behavioural test change (DataTests now never runs concurrently with the other classes), and the `[Collection("Milvus")]` removal in Bm25Tests.cs is also unmentioned. Worth updating the description so the scope and the FlushAll-race rationale are discoverable from the PR record — the "No behavioural change" claim is no longer accurate for the test suite.

File: Milvus.Client.Tests/Bm25Tests.cs (hunk 1 above)
Comment (N-E-W-T-O-N) [reply Milvus.Client.Tests/Bm25Tests.cs]: Good catch — fixed in 1ae3b18.

You are right that none of these calls skips an optional parameter (`parameters` is always supplied), so positional is the form that matches the stated rule. Unified the four named ones with the four already positional.

Kept the named form only where an optional parameter genuinely is skipped: `CreateIndexAsync` passing `extraParams:` without `indexName`, `CreateCollectionAsync` skipping `consistencyLevel`/`shardsNum`, `InsertAsync` skipping `partitionName`, and `LoadAsync` skipping `replicaNumber`.

File: Milvus.Client.Tests/DataTests.cs (hunk 2 above)
Comment (N-E-W-T-O-N) [reply Milvus.Client.Tests/DataTests.cs:9]: Agreed, and updated — the PR title and description now cover both changes.

For context: the description you saw was the original one ("Thread cancellation tokens through Bm25Tests"). The `DisableParallelization` change and the `[Collection("Milvus")]` removal were added after that, when the second CI failure appeared, and the title/body have since been rewritten to cover the FlushAll race and its rationale.

I have also tightened the wording you flagged: "No behavioural change" now scopes explicitly to the token-threading item, and there is a note calling out that items 2 and 3 *are* behavioural test changes — `DataTests` no longer runs concurrently with the other classes.
